# Generated by Django 6.0.1 on 2026-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=17)),
                ('rssi', models.IntegerField()),
                ('raw_data', models.TextField()),
                ('is_ibeacon', models.BooleanField(default=False)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('major', models.IntegerField(blank=True, null=True)),
                ('minor', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
