# Generated by Django 6.0.1 on 2026-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='device_timestamp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='beaconlog',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
    ]
