# Generated by Django 6.0.1 on 2026-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_presence', '0002_beaconlog_device_timestamp_alter_beaconlog_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
