# Generated by Django 6.0.1 on 2026-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_presence', '0003_beaconlog_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='scanner_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
