# Generated by Django 6.0.1 on 2026-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_presence', '0004_beaconlog_scanner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='assigned_location',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
